# Generated by Django 2.2.6 on 2019-11-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlib', '0002_remove_genre_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='Date of death'),
        ),
        migrations.AlterField(
            model_name='book',
            name='page_amount',
            field=models.IntegerField(verbose_name='Amount page book'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.CharField(max_length=255, verbose_name="Book's genre"),
        ),
    ]
