# Generated by Django 2.2.6 on 2019-11-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlib', '0004_auto_20191104_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='First name'),
        ),
    ]
